grid_search:
  KMeans:
    n_clusters: [2, 3, 4, 5, 6, 7, 8]
    init: ['k-means++', 'random']
    max_iter: [300, 500]
    random_state: [42]
  
  AgglomerativeClustering:
    n_clusters: [2, 3, 4, 5, 6, 7, 8]
    linkage: ['ward', 'complete', 'average']
  
  DBSCAN:
    eps: [0.1, 0.3, 0.5, 0.7, 1.0]
    min_samples: [3, 5, 8, 10]

evaluation_metrics:
  - silhouette_score
  - calinski_harabasz_score
  - davies_bouldin_score

model_selection:
  cv: 5
  scoring: silhouette_score
  n_jobs: -1